# site name
prefixName: TSHMF
siteName: 变嫁
# favicon and site master avatar
favicon: /2022/12/12/ig46538xuMZSAhD.png
avatar: /2022/12/12/aidWrcKlFTyx2UH.jpg
url: https://adk23333.github.io/
description: 为每一个热爱变嫁的人干杯！
cdn: https://s2.loli.net
pjax: 1
# 1开启
mathjax: 0

notice: 站点更新中......
lazyloadImg: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/loader/orange.progress-bar-stripe-loader.svg

menus:
  首页: { path: /, fa: fa-fort-awesome faa-shake }
  归档: { path: /archives, fa: fa-archive faa-shake, submenus: { 
    技术: {path: /categories/技术/, fa: fa-code }, 
    生活: {path: /categories/生活/, fa: fa-file-text-o }, 
    资源: {path: /categories/资源/, fa: fa-cloud-download }, 
    随想: {path: /categories/随想/, fa: fa-commenting-o },
    转载: {path: /categories/转载/, fa: fa-book }
  } }
  清单: { path: javascript:;, fa: fa-list-ul faa-vertical, submenus: { 
    书单: {path: /tags/悦读/, fa: fa-th-list faa-bounce }, 
    番组: {path: /bangumi/, fa: fa-film faa-vertical }, 
    图集: {path: /tags/图集/, fa: fa-photo }
  } }
  留言板: { path: /comment/, fa: fa-pencil-square-o faa-tada }
  友人帐: { path: /links/, fa: fa-link faa-shake }
  赞赏: { path: /donate/, fa: fa-heart faa-pulse }
  关于: { path: /, fa: fa-leaf faa-wrench , submenus: { 
    我？: {path: /about/, fa: fa-meetup}, 
    主题: {path: /theme-sakura/, fa: iconfont icon-sakura },
    Lab: {path: /lab/, fa: fa-cogs },
  } }
  客户端: { path: /client/, fa: fa-android faa-vertical }
  RSS: { path: /atom.xml, fa: fa-rss faa-pulse }


# Home page sort type: -1: newer first，1: older first.
homePageSortType: -1
# Home page article shown number)
homeArticleShown: 10
# 背景图片 更好的修改
bg:
  - https://s2.loli.net/2022/12/12/acS21jkmx6Ue5WF.webp

# 背景图片样式 空 原图效果 filter-dim 阴影 filter-grid 横条 filter-dot 点点
bgclass: filter-dot

# startdash url, title, desc img
startdash: 
  - {url: https://www.bilibili.com/, title: BiliBili, desc: 我们的B站号, img: /2022/12/12/we48MZhVGrk3t52.webp}
  - {url: https://tieba.baidu.com/home/main?un=adk23333&id=tb.1.9f5a63a2.w1s__jfQF2ejxoCf1OCcmw?t=1533450011&fr=index, title: BaiduTieba, desc: 博主的贴吧个人主页, img: /2022/12/12/cMhpNAx6DKL4rHE.jpg}
  - {url: https://jq.qq.com/?_wv=1027&k=gXwoukxn, title: 爱与正义的咸鱼少女团, desc: 变嫁同好交流群, img: /2022/12/12/XMzCFcKdoq7PmVb.jpg}



# your site build time or founded date
siteBuildingTime: 12/12/2022

#social  url, img PC端配置
social:
  github: {url: https://github.com/adk23333, img: /2022/12/14/T8ueMnROSBDIFih.png}
  tieba: {url: https://tieba.baidu.com/f?kw=%E5%8F%98%E8%BA%AB%E5%AB%81%E4%BA%BA%E5%B0%8F%E8%AF%B4&fr=index, img: /2022/12/12/7f6H1theoLq8lNj.png}

#social  url, img 移动端配置
msocial:
  github: {url: https://github.com/adk23333, fa: fa-github, color: 333}
  tieba: {url: https://tieba.baidu.com/f?kw=%E5%8F%98%E8%BA%AB%E5%AB%81%E4%BA%BA%E5%B0%8F%E8%AF%B4&fr=index, img: /2022/12/12/7f6H1theoLq8lNj.png}

donate:
  paypal: https://www.paypal.me/hojuncn
  alipay: /img/custom/donate/AliPayQR.jpg
  wechat: /img/custom/donate/WeChanQR.jpg
  wechatSQ: /img/custom/donate/WeChanSQ.jpg

# 视频地址为https://cdn.jsdelivr.net/gh/honjun/hojun@1.2/Unbroken.mp4，配置如下
movies:
  url: https://cdn.jsdelivr.net/gh/honjun/hojun@1.2
  # 多个视频用逗号隔开，随机获取。支持的格式目前已知MP4,Flv。其他的可以试下，不保证有用
  name: Unbroken.mp4

aplayer: 
  id: 2660651585
  server: netease
  type: playlist
  fixed: true
  autoplay: false
  loop: all
  order: random
  preload: auto
  volume: 0.7
  mutex: true

# Valine
valine: true
v_appId: jw7T7b7mW8xVxLWvGIQhfztb-gzGzoHsz
v_appKey: F1CKL6PcOp1jOJzwoVp9qhAp

# Waline
waline:
  enable: false
  serverURL: #服务端地址
  visitor: false #统计阅读量
  comment_count: true #统计评论数
  avatar: mp # Gravatar style : mp/identicon/monsterid/wavatar/retro/hide
  guest_info: nick #,mail,link # custom comment header
  pageSize: 10
  placeholder: 祝开开心心！ # Comment Box placeholder
  requiredFields: [ 'nick','mail' ] #设置必填项
  background: https://gitee.com/cungudafa/source/raw/master/img/gif/Sitich/Sitich2.gif #输入框提示动画